name: Build and Release DLL

on:
  push:

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install MinGW-w64 (x86_64-w64-mingw32-gcc)
        run: sudo apt-get update && sudo apt-get install -y mingw-w64

      - name: Compile project
        run: sh compile.sh

      - name: Check for DLL presence
        id: check_dll
        run: |
          if [ -f "PieHid64.dll" ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Create GitHub Release
        if: steps.check_dll.outputs.exists == 'true'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.sha }}
          name: Build ${{ github.sha }}
          files: PieHid64.dll
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
